### ISSUE TITLE
Binary output

### ISSUE THREAD

**Issue by artrag** [cornelisser/TriloTracker-Re-player#3]
Would it be possible to produce the compiled music as binary file ready to be compressed ?

**Comment by cornelisser** [comment]
Hi,

Well. As music data and pointers are relative it is easier to produce 
asm data instead of direct binairy data.
It will be possible to set the start address of the music in the 
compiler in a newer version. It is now set on $c000 in default and is 
commented out.
With the new option It could be able to call sjasm to compile the data 
from within the compiler.

Regards,
Richard

**Comment by artrag** [comment]
Probably the simplest thing to do would be to add to the ASM output a couple of lines of header to allow sjasm to assemble a binary file at a given address, than run sjasm in a batch and get the binary result.
